/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MoodType = IDL.Variant({
  'happy' : IDL.Null,
  'chill' : IDL.Null,
  'gaming' : IDL.Null,
  'firedUp' : IDL.Null,
  'chaotic' : IDL.Null,
  'drained' : IDL.Null,
});
export const MoodEntry = IDL.Record({
  'mood' : MoodType,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'logMood' : IDL.Func([MoodType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MoodType = IDL.Variant({
    'happy' : IDL.Null,
    'chill' : IDL.Null,
    'gaming' : IDL.Null,
    'firedUp' : IDL.Null,
    'chaotic' : IDL.Null,
    'drained' : IDL.Null,
  });
  const MoodEntry = IDL.Record({ 'mood' : MoodType, 'timestamp' : IDL.Int });
  
  return IDL.Service({
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'logMood' : IDL.Func([MoodType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };