/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MoodEntry {
    mood: MoodType;
    timestamp: bigint;
}
export enum MoodType {
    happy = "happy",
    chill = "chill",
    gaming = "gaming",
    firedUp = "firedUp",
    chaotic = "chaotic",
    drained = "drained"
}
export interface backendInterface {
    getMoodHistory(): Promise<Array<MoodEntry>>;
    logMood(mood: MoodType): Promise<void>;
}
import type { MoodEntry as _MoodEntry, MoodType as _MoodType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getMoodHistory(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodHistory();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodHistory();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async logMood(arg0: MoodType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMood(to_candid_MoodType_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMood(to_candid_MoodType_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_MoodEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodEntry): MoodEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MoodType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodType): MoodType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood: _MoodType;
    timestamp: bigint;
}): {
    mood: MoodType;
    timestamp: bigint;
} {
    return {
        mood: from_candid_MoodType_n4(_uploadFile, _downloadFile, value.mood),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    happy: null;
} | {
    chill: null;
} | {
    gaming: null;
} | {
    firedUp: null;
} | {
    chaotic: null;
} | {
    drained: null;
}): MoodType {
    return "happy" in value ? MoodType.happy : "chill" in value ? MoodType.chill : "gaming" in value ? MoodType.gaming : "firedUp" in value ? MoodType.firedUp : "chaotic" in value ? MoodType.chaotic : "drained" in value ? MoodType.drained : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoodEntry>): Array<MoodEntry> {
    return value.map((x)=>from_candid_MoodEntry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_MoodType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodType): _MoodType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodType): {
    happy: null;
} | {
    chill: null;
} | {
    gaming: null;
} | {
    firedUp: null;
} | {
    chaotic: null;
} | {
    drained: null;
} {
    return value == MoodType.happy ? {
        happy: null
    } : value == MoodType.chill ? {
        chill: null
    } : value == MoodType.gaming ? {
        gaming: null
    } : value == MoodType.firedUp ? {
        firedUp: null
    } : value == MoodType.chaotic ? {
        chaotic: null
    } : value == MoodType.drained ? {
        drained: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
